- name: Set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ rancher_kernel_modules }}"
