---
# defaults file for rancher_prep
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg
docker_users: []
rancher_kernel_modules:
  - br_netfilter
  - ip6_udp_tunnel
  - ip_set
  - ip_set_hash_ip
  - ip_set_hash_net
  - iptable_filter
  - iptable_nat
  - iptable_mangle
  - iptable_raw
  - nf_conntrack_netlink
  - nf_conntrack
  - nf_conntrack_ipv4
  - nf_defrag_ipv4
  - nf_nat
  - nf_nat_ipv4
  - nf_nat_masquerade_ipv4
  - nfnetlink
  - udp_tunnel
  - veth
  - vxlan
#  - x_tables # built in see /lib/modules/$(uname -r)/modules.builtin
  - xt_addrtype
  - xt_conntrack
  - xt_comment
  - xt_mark
  - xt_multiport
  - xt_nat
  - xt_recent
  - xt_set
  - xt_statistic
#  - xt_tcpudp # built in see /lib/modules/$(uname -r)/modules.builtin
#
rancher_prep_update_ca_certs: 'no'
rancher_prep_ca_certs: []

